import {
  Barangay,
  User,
  IncidentReport,
  Corroboration,
  Advisory,
  EvacuationCenter,
  EmergencyHotline,
  SystemAuditLog
} from '../types';

export const INITIAL_BARANGAYS: Barangay[] = [
  {
    id: 'poblacion',
    name: 'Poblacion',
    city: 'Lingayen',
    latitude: 16.0234,
    longitude: 120.2289,
    population: 14200,
    risk_level: 'moderate',
  },
  {
    id: 'maniboc',
    name: 'Maniboc',
    city: 'Lingayen',
    latitude: 16.0352,
    longitude: 120.2215,
    population: 8900,
    risk_level: 'high', // Coastal
  },
  {
    id: 'libsong',
    name: 'Libsong',
    city: 'Lingayen',
    latitude: 16.0315,
    longitude: 120.2412,
    population: 7600,
    risk_level: 'critical', // Low-lying & coastal surge
  },
  {
    id: 'baay',
    name: 'Baay',
    city: 'Lingayen',
    latitude: 16.0112,
    longitude: 120.2195,
    population: 9400,
    risk_level: 'high', // River overflow
  },
  {
    id: 'domalandan_center',
    name: 'Domalandan Center',
    city: 'Lingayen',
    latitude: 16.0025,
    longitude: 120.1984,
    population: 6200,
    risk_level: 'low',
  },
  {
    id: 'pangapisan_north',
    name: 'Pangapisan North',
    city: 'Lingayen',
    latitude: 16.0398,
    longitude: 120.2110,
    population: 5800,
    risk_level: 'high',
  },
  {
    id: 'pangapisan_sur',
    name: 'Pangapisan Sur',
    city: 'Lingayen',
    latitude: 16.0310,
    longitude: 120.2085,
    population: 6400,
    risk_level: 'critical',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_citizen_1',
    full_name: 'Juan Dela Cruz',
    email: 'juan.delacruz@lingayen.ph',
    role: 'citizen',
    barangay_id: 'libsong',
    created_at: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'usr_citizen_2',
    full_name: 'Maria Santos',
    email: 'maria.santos@gmail.com',
    role: 'citizen',
    barangay_id: 'libsong',
    created_at: '2026-09-05T09:15:00.000Z',
  },
  {
    id: 'usr_citizen_3',
    full_name: 'Roberto Gomez',
    email: 'roberto.gomez@gmail.com',
    role: 'citizen',
    barangay_id: 'libsong',
    created_at: '2026-09-10T14:30:00.000Z',
  },
  {
    id: 'usr_barangay_libsong',
    full_name: 'Kagawad Elena Reyes (BDRRMC)',
    email: 'elena.reyes@libsong.lingayen.gov.ph',
    role: 'barangay',
    barangay_id: 'libsong',
    created_at: '2026-08-15T10:00:00.000Z',
  },
  {
    id: 'usr_barangay_poblacion',
    full_name: 'Capt. Danilo Fernandez (BDRRMC)',
    email: 'danilo.fernandez@poblacion.lingayen.gov.ph',
    role: 'barangay',
    barangay_id: 'poblacion',
    created_at: '2026-08-15T10:00:00.000Z',
  },
  {
    id: 'usr_lgu_admin',
    full_name: 'Lebron Dwayne Cervantes',
    email: 'ldrmo.officer@lingayen.gov.ph',
    role: 'lgu_admin',
    barangay_id: undefined,
    created_at: '2026-08-01T08:00:00.000Z',
  },
];

export const INITIAL_REPORTS: IncidentReport[] = [
  {
    id: 'rep_100a',
    reporter_id: 'usr_citizen_1',
    reporter_name: 'Resident Caller (Pangapisan Sur)',
    barangay_id: 'pangapisan_sur',
    hazard_type: 'Emergency SOS',
    description: 'One-Tap SOS Activated at phone coordinates: 16.0310, 120.2085. Trapped residents along shoreline sector requesting immediate rescue.',
    latitude: 16.0310,
    longitude: 120.2085,
    status: 'unverified',
    corroboration_count: 0,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000 - 15 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000 - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'rep_100b',
    reporter_id: 'usr_citizen_2',
    reporter_name: 'Barangay Watcher (Pangapisan Sur)',
    barangay_id: 'pangapisan_sur',
    hazard_type: 'Emergency SOS',
    description: 'One-Tap SOS Activated at phone coordinates: 16.0305, 120.2090. Rapid water surge blocking residential exit routes.',
    latitude: 16.0305,
    longitude: 120.2090,
    status: 'unverified',
    corroboration_count: 0,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000 - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000 - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'rep_101',
    reporter_id: 'usr_citizen_1',
    reporter_name: 'Juan Dela Cruz',
    barangay_id: 'libsong',
    hazard_type: 'Flood',
    description: 'Rapidly rising knee-deep water along coastal road near fish port due to combined high tide and torrential rain.',
    photo_url: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80',
    latitude: 16.0322,
    longitude: 120.2425,
    status: 'verified', // Pre-corroborated by 3 citizens
    corroboration_count: 3,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    dispatch_notes: 'BDRRMC Libsong rescue team preparing rubber boat staging.',
  },
  {
    id: 'rep_102',
    reporter_id: 'usr_citizen_2',
    reporter_name: 'Maria Santos',
    barangay_id: 'poblacion',
    hazard_type: 'Downed Powerline',
    description: 'Electric cable snapped across Avenida Rizal East near Capitol Grounds. Live sparks observed. Road impassable to light vehicles.',
    photo_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=80',
    latitude: 16.0248,
    longitude: 120.2298,
    status: 'dispatched',
    corroboration_count: 2,
    created_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    assigned_team: 'PANELCO I Emergency Linemen & BFP Lingayen',
    dispatch_notes: 'Units arrived on site, perimeter secured with yellow tape.',
  },
  {
    id: 'rep_103',
    reporter_id: 'usr_citizen_3',
    reporter_name: 'Roberto Gomez',
    barangay_id: 'baay',
    hazard_type: 'Road Obstruction',
    description: 'Large uprooted Talisay tree blocking both lanes of provincial secondary road going to Domalandan bridge.',
    photo_url: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80',
    latitude: 16.0125,
    longitude: 120.2180,
    status: 'unverified',
    corroboration_count: 1,
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 'rep_104',
    reporter_id: 'usr_citizen_1',
    reporter_name: 'Juan Dela Cruz',
    barangay_id: 'maniboc',
    hazard_type: 'Storm Surge',
    description: 'Strong waves breaching sea dike barriers at Lingayen Beach Park shoreline. Fisherfolk evacuated bangkas.',
    photo_url: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&w=800&q=80',
    latitude: 16.0360,
    longitude: 120.2220,
    status: 'unverified',
    corroboration_count: 2,
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'rep_105',
    reporter_id: 'usr_citizen_2',
    reporter_name: 'Maria Santos',
    barangay_id: 'domalandan_center',
    hazard_type: 'Flood',
    description: 'Creek swelling near agricultural drainage canal. Minor spillover to roadside.',
    latitude: 16.0030,
    longitude: 120.1990,
    status: 'resolved',
    corroboration_count: 3,
    created_at: new Date(Date.now() - 360 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    assigned_team: 'Barangay Maintenance Crew',
    resolution_notes: 'Debris cleared from culvert gate. Water receding normally.',
    resolved_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
  },
  {
    id: 'rep_106',
    reporter_id: 'usr_citizen_3',
    reporter_name: 'Caller (Baay District)',
    barangay_id: 'baay',
    hazard_type: 'Flood',
    description: 'Reported impassable road near sports arena. BDRRMC on-site patrol verified clear; false alert dismissed.',
    latitude: 16.0140,
    longitude: 120.2190,
    status: 'rejected',
    corroboration_count: 0,
    created_at: new Date(Date.now() - 480 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 400 * 60 * 1000).toISOString(),
    resolution_notes: 'Patrol dispatched. Verified normal pavement conditions, no standing water.',
  },
];

export const INITIAL_CORROBORATIONS: Corroboration[] = [
  {
    id: 'corrob_1',
    report_id: 'rep_101',
    user_id: 'usr_citizen_1',
    user_name: 'Juan Dela Cruz',
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    comment: 'Initial report submitted with GPS.',
  },
  {
    id: 'corrob_2',
    report_id: 'rep_101',
    user_id: 'usr_citizen_2',
    user_name: 'Maria Santos',
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    comment: 'Confirming! Water has reached inside our yard at Zone 3.',
  },
  {
    id: 'corrob_3',
    report_id: 'rep_101',
    user_id: 'usr_citizen_3',
    user_name: 'Roberto Gomez',
    created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    comment: 'Verified from my store nearby. Tricycles cannot pass through.',
  },
  {
    id: 'corrob_4',
    report_id: 'rep_102',
    user_id: 'usr_citizen_2',
    user_name: 'Maria Santos',
    created_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
  },
  {
    id: 'corrob_5',
    report_id: 'rep_102',
    user_id: 'usr_citizen_1',
    user_name: 'Juan Dela Cruz',
    created_at: new Date(Date.now() - 85 * 60 * 1000).toISOString(),
    comment: 'I heard the loud pop when the transformer blew.',
  },
  {
    id: 'corrob_6',
    report_id: 'rep_104',
    user_id: 'usr_citizen_1',
    user_name: 'Juan Dela Cruz',
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'corrob_7',
    report_id: 'rep_104',
    user_id: 'usr_citizen_2',
    user_name: 'Maria Santos',
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    comment: 'Waves are splashing over the pedestrian seawall.',
  }
];

export const INITIAL_ADVISORIES: Advisory[] = [
  {
    id: 'adv_pangapisan_overflow',
    author_id: 'usr_lgu_admin',
    author_name: 'MDRRMO Incident Commander',
    title: 'River Overflow Warning: Pangapisan North',
    content: 'Water levels are rising near Pangapisan North. Residents near the shoreline are advised to prepare for possible evacuation.',
    type: 'emergency_alert',
    severity: 'critical',
    target_barangay_id: 'pangapisan_north',
    created_at: '2026-09-19T08:30:00.000Z',
  },
  {
    id: 'adv_class_suspension',
    author_id: 'usr_lgu_admin',
    author_name: 'Office of the Municipal Mayor / MDRRMC',
    title: 'Suspension of Classes, All Levels',
    content: 'Due to severe weather conditions and localized flood hazards across low-lying barangays, classes in all levels (public and private) and municipal government work are suspended until further notice.',
    type: 'emergency_alert',
    severity: 'high',
    target_barangay_id: null,
    created_at: '2026-09-19T06:00:00.000Z',
  },
  {
    id: 'adv_coastal_surge',
    author_id: 'usr_lgu_admin',
    author_name: 'LDRRMC Maritime Safety Division',
    title: 'Coastal Advisory: Storm Surge Watch',
    content: 'High tide combined with southwest gale winds will cause wave swells of 3.0 to 4.5 meters along coastal barangays. All sea travel and small-craft fishing operations are strictly prohibited.',
    type: 'emergency_alert',
    severity: 'high',
    target_barangay_id: null,
    created_at: '2026-09-19T05:15:00.000Z',
  },
  {
    id: 'adv_drill_nsed',
    author_id: 'usr_lgu_admin',
    author_name: 'LDRRMC Preparedness Division',
    title: 'Preparedness Drill: Duck, Cover, Hold',
    content: 'Quarterly municipal earthquake and tsunami preparedness drill scheduled. Practice evacuation routes to your barangay multi-purpose center. Remember Duck, Cover, and Hold.',
    type: 'preparedness',
    severity: 'medium',
    target_barangay_id: null,
    created_at: '2026-09-17T09:00:00.000Z',
  },
  {
    id: 'adv_gobag_checklist',
    author_id: 'usr_lgu_admin',
    author_name: 'LDRRMC Public Information Office',
    title: 'Go-Bag Checklist for the Wet Season',
    content: 'Prepare your 72-hour family emergency go-bag: 3-day non-perishable food, potable drinking water (1 gal/person/day), waterproof pouch for official IDs and land titles, flashlight, battery radio, and first-aid kits.',
    type: 'preparedness',
    severity: 'low',
    target_barangay_id: null,
    created_at: '2026-09-15T14:00:00.000Z',
  },
  {
    id: 'adv_1',
    author_id: 'usr_lgu_admin',
    author_name: 'Engr. Jonathan Ramos (LDRRMO)',
    title: 'RED ALERT: Severe Tropical Storm Gale Warning & Coastal Evacuation Advisory',
    content: 'PAGASA has issued Tropical Cyclone Wind Signal No. 2 over Pangasinan. Lingayen Gulf waters are experiencing gale-force waves (3.5m to 5.0m). Residents in coastal barangays Libsong, Maniboc, and Pangapisan North are advised to execute preemptive evacuation to designated shelters.',
    type: 'emergency_alert',
    severity: 'critical',
    target_barangay_id: null, // City-wide
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'adv_2',
    author_id: 'usr_barangay_libsong',
    author_name: 'BDRRMC Libsong Operations Desk',
    title: 'Barangay Libsong Preemptive Evacuation Staging Live',
    content: 'Libsong Elementary School Evacuation Center is now OPEN. Shuttle vehicles are stationed at Zone 2 Chapel and Zone 4 Basketball Court. Bring essential go-bags and medicines.',
    type: 'emergency_alert',
    severity: 'high',
    target_barangay_id: 'libsong',
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_EVACUATION_CENTERS: EvacuationCenter[] = [
  {
    id: 'evac_1',
    hash_id: 'ddf15781-161a-4a91-9f74-6a3d355bc825',
    barangay_id: 'libsong',
    name: 'Libsong Elementary School',
    address: 'Libsong East, Lingayen, Pangasinan',
    capacity: 400,
    current_occupancy: 0,
    status: 'open',
    facilities: ['Covered Classrooms', 'Sanitation Facility', 'Water Storage Tank'],
    contact_person: 'Barangay Relief Coordinator',
    contact_number: '0917-234-9988',
    latitude: 16.02850,
    longitude: 120.23900,
    notes: 'Coordinates are estimated (barangay centroid) — reconfirm with MDRRMO GIS before relying on for routing.',
  },
  {
    id: 'evac_2',
    hash_id: '25abc426-c035-4a24-a930-74e8b66cd51b',
    barangay_id: 'poblacion',
    name: 'Lingayen Civic Center / Evacuation Center',
    address: 'Poblacion, Lingayen, Pangasinan',
    capacity: 650,
    current_occupancy: 620,
    status: 'open',
    facilities: ['Backup Generator Set', 'Community Kitchen', 'Medical Infirmary', 'WiFi Station'],
    contact_person: 'Admin Officer Mario Valdez',
    contact_number: '0917-555-8910',
    latitude: 16.01883,
    longitude: 120.22815,
    notes: 'Coordinates sourced from OpenStreetMap-aligned data.',
  },
  {
    id: 'evac_3',
    hash_id: 'dbcda1de-749a-4933-b45a-40f906cede9e',
    barangay_id: 'pangapisan_north',
    name: 'PAGCOR Multi-Purpose Evacuation Center (MPEC)',
    address: 'Pangapisan North, Lingayen, Pangasinan',
    capacity: 1000,
    current_occupancy: 0,
    status: 'full',
    facilities: ['Multi-Storey Evacuation Complex', 'Solar Power Back-up', 'Industrial Kitchen'],
    contact_person: 'MDRRMO Site Liaison',
    contact_number: '0920-888-2134',
    latitude: 16.03580,
    longitude: 120.21980,
    notes: 'Coordinates are estimated (barangay centroid) — reconfirm with MDRRMO GIS before relying on for routing.',
  },
  {
    id: 'evac_4',
    hash_id: '851bb3ad-792e-470c-b3d9-1c167bc6b0f2',
    barangay_id: 'pangapisan_sur',
    name: 'Pangapisan Elementary School',
    address: 'Pangapisan Sur, Lingayen, Pangasinan',
    capacity: 400,
    current_occupancy: 0,
    status: 'closed',
    facilities: ['Classrooms', 'Covered Walkways'],
    contact_person: 'School Disaster Coordinator',
    contact_number: '0918-990-1234',
    latitude: 16.02346,
    longitude: 120.21505,
    notes: 'Coordinates sourced from OpenStreetMap-aligned data.',
  },
  {
    id: 'evac_5',
    hash_id: '090352cf-7c69-4e74-8c8d-ada498a7a2c2',
    barangay_id: 'poblacion',
    name: 'Pangasinan Training Center / Disaster Evacuation Facility',
    address: 'Poblacion, Lingayen, Pangasinan',
    capacity: 600,
    current_occupancy: 0,
    status: 'closed',
    facilities: ['Auditorium Hall', 'Lactation Room', 'Charging Hub'],
    contact_person: 'PTC Facility Manager',
    contact_number: '0995-123-4567',
    latitude: 16.02100,
    longitude: 120.23150,
    notes: 'Coordinates reported as verified by source; still recommend a spot-check.',
  },
];

export const INITIAL_HOTLINES: EmergencyHotline[] = [
  {
    id: 'hotline_1',
    agency_name: 'BFP Lingayen',
    contact_number: '(075) 542-7080',
    scope: 'Fire',
    tag: 'FIRE AND RESCUE',
    description: 'Bureau of Fire Protection - Fire response, rescue operations, and hazardous material containment',
    priority: 1,
    available_hours: '24/7 Always Open',
  },
  {
    id: 'hotline_2',
    agency_name: 'Lingayen MDRRMO',
    contact_number: '(075) 633-5702',
    scope: 'Municipal',
    description: 'Municipal Disaster Risk Reduction & Management Office - Central emergency dispatch, rescue and relief coordination',
    priority: 2,
    available_hours: '24/7 Central Emergency Desk',
  },
  {
    id: 'hotline_3',
    agency_name: "Mayor's Office Emergency Desk",
    contact_number: '(075) 632-4337',
    scope: 'Municipal',
    description: 'Office of the Municipal Mayor - Public assistance, disaster relief directives, and administrative emergency support',
    priority: 3,
    available_hours: '24/7 Calamity Operations',
  },
  {
    id: 'hotline_4',
    agency_name: 'National Emergency Hotline',
    contact_number: '911',
    scope: 'National',
    description: 'National Emergency Hotline - Nationwide immediate emergency response dispatch',
    priority: 4,
    available_hours: '24/7 Toll-Free Emergency',
  },
  {
    id: 'hotline_5',
    agency_name: 'Pangasinan PDRRMO',
    contact_number: '0998-584-6867',
    scope: 'Provincial',
    tag: 'PROVINCIAL SUPPORT',
    description: 'Provincial Disaster Risk Reduction & Management Office - Heavy rescue equipment and inter-municipal support',
    priority: 5,
    available_hours: '24/7 Provincial Operations',
  },
  {
    id: 'hotline_6',
    agency_name: 'PNP Lingayen',
    contact_number: '(075) 206-0042',
    scope: 'Police',
    tag: 'POLICE ASSISTANCE',
    description: 'Philippine National Police - Law enforcement, security patrols, evacuation order enforcement',
    priority: 6,
    available_hours: '24/7 Police Assistance',
  },
  {
    id: 'hotline_7',
    agency_name: 'Provincial Health Office',
    contact_number: '0933-813-8623',
    scope: 'Hospital',
    tag: 'MEDICAL AND RELIEF',
    description: 'Pangasinan Provincial Health Office - Emergency medical services, triage dispatch, and disease surveillance',
    priority: 7,
    available_hours: '24/7 Medical Response',
  },
];

export const INITIAL_AUDIT_LOGS: SystemAuditLog[] = [
  {
    id: 'log_1',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    event_type: 'crowd_corroboration_auto_verify',
    actor_name: 'System Engine',
    description: 'Report #rep_101 auto-verified after reaching 3 corroborations from independent citizens within Libsong.',
    target_id: 'rep_101',
  },
  {
    id: 'log_2',
    timestamp: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    event_type: 'status_dispatch',
    actor_name: 'Capt. Danilo Fernandez (BDRRMC)',
    description: 'Dispatched PANELCO I Linemen & BFP Lingayen to Downed Powerline on Avenida Rizal East.',
    target_id: 'rep_102',
  },
  {
    id: 'log_3',
    timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    event_type: 'emergency_broadcast',
    actor_name: 'Engr. Jonathan Ramos (LDRRMO Chief)',
    description: 'Broadcasted CRITICAL RED ALERT for Severe Tropical Storm Gale Warning city-wide.',
    target_id: 'adv_1',
  },
];
